apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","metadata":{"annotations":{"meta.helm.sh/release-name":"kube-prom-stack","meta.helm.sh/release-namespace":"monitoring"},"labels":{"app":"kube-prometheus-stack-prometheus","app.kubernetes.io/instance":"kube-prom-stack","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/part-of":"kube-prometheus-stack","app.kubernetes.io/version":"80.11.0","chart":"kube-prometheus-stack-80.11.0","heritage":"Helm","release":"kube-prom-stack"},"name":"kube-prom-stack-kube-prome-prometheus","namespace":"monitoring"},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["prometheus"]},{"key":"app.kubernetes.io/instance","operator":"In","values":["kube-prom-stack-kube-prome-prometheus"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"alerting":{"alertmanagers":[{"apiVersion":"v2","name":"kube-prom-stack-kube-prome-alertmanager","namespace":"monitoring","pathPrefix":"/","port":"http-web"}]},"automountServiceAccountToken":true,"enableAdminAPI":false,"enableOTLPReceiver":false,"evaluationInterval":"30s","externalLabels":{"cluster":"cluster-b"},"externalUrl":"http://kube-prom-stack-kube-prome-prometheus.monitoring:9090","hostNetwork":false,"image":"quay.io/prometheus/prometheus:v3.8.1","imagePullPolicy":"IfNotPresent","listenLocal":false,"logFormat":"logfmt","logLevel":"info","paused":false,"podMonitorNamespaceSelector":{},"podMonitorSelector":{"matchLabels":{"release":"kube-prom-stack"}},"portName":"http-web","probeNamespaceSelector":{},"probeSelector":{"matchLabels":{"release":"kube-prom-stack"}},"remoteWrite":[{"queueConfig":{"capacity":20000,"maxSamplesPerSend":10000,"maxShards":30},"url":"http://98.70.41.123:8480/insert/0/prometheus/api/v1/write"}],"replicas":1,"retention":"10d","routePrefix":"/","ruleNamespaceSelector":{},"ruleSelector":{"matchLabels":{"release":"kube-prom-stack"}},"scrapeConfigNamespaceSelector":{},"scrapeConfigSelector":{"matchLabels":{"release":"kube-prom-stack"}},"scrapeInterval":"30s","securityContext":{"fsGroup":2000,"runAsGroup":2000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"kube-prom-stack-kube-prome-prometheus","serviceMonitorNamespaceSelector":{},"serviceMonitorSelector":{"matchLabels":{"release":"kube-prom-stack"}},"shards":1,"thanos":{"blockSize":"2h","objectStorageConfig":{"key":"objstore.yaml","name":"thanos-objstore"},"version":"v0.40.0"},"tsdb":{"outOfOrderTimeWindow":"0s"},"version":"v3.8.1","walCompression":true},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2026-01-07T11:11:53Z","message":"","observedGeneration":4,"reason":"","status":"True","type":"Available"},{"lastTransitionTime":"2026-01-07T11:11:53Z","message":"","observedGeneration":4,"reason":"","status":"True","type":"Reconciled"}],"paused":false,"replicas":1,"selector":"app.kubernetes.io/instance=kube-prom-stack-kube-prome-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=kube-prom-stack-kube-prome-prometheus,prometheus=kube-prom-stack-kube-prome-prometheus","shardStatuses":[{"availableReplicas":1,"replicas":1,"shardID":"0","unavailableReplicas":0,"updatedReplicas":1}],"shards":1,"unavailableReplicas":0,"updatedReplicas":1}}
    meta.helm.sh/release-name: kube-prom-stack
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.11.0
    chart: kube-prometheus-stack-80.11.0
    heritage: Helm
    release: kube-prom-stack
  name: kube-prom-stack-kube-prome-prometheus
  namespace: monitoring
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - prometheus
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - kube-prom-stack-kube-prome-prometheus
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: kube-prom-stack-kube-prome-alertmanager
      namespace: monitoring
      pathPrefix: /
      port: http-web
  automountServiceAccountToken: true
  enableAdminAPI: false
  enableOTLPReceiver: false
  evaluationInterval: 30s
---------------------------------->>>>>>>>
  externalLabels: 
    vm_account_id: "2" 
    cluster: "cluster-b"
---------------------------------->>>>>>>>
  externalUrl: http://kube-prom-stack-kube-prome-prometheus.monitoring:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v3.8.1
  imagePullPolicy: IfNotPresent
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: kube-prom-stack
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: kube-prom-stack
---------------------------------->>>>>>>>
  remoteWrite:  
  - queueConfig:
      capacity: 20000
      maxSamplesPerSend: 10000
      maxShards: 30
    url: http://98.70.41.123:8480/insert/multitenant/prometheus/api/v1/write 
---------------------------------->>>>>>>>
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: kube-prom-stack
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: kube-prom-stack
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: kube-prom-stack-kube-prome-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: kube-prom-stack
  shards: 1
  thanos:
    blockSize: 2h
    objectStorageConfig:
      key: objstore.yaml
      name: thanos-objstore
    version: v0.40.0
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v3.8.1
  walCompression: true
